name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 23 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: yetone
          base: header, activity, repositories, metadata
          config_timezone: Asia/Shanghai
          repositories_skipped: yetone
          optimize: svg
          experimental_features: --optimize-svg
          
          plugin_isocalendar: yes
          
          plugin_languages: yes
          plugin_languages_ignored: javascript, html, css
          plugin_languages_limit: 5
          
          plugin_lines: yes
          
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist

          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: yetone
